### ISSUE TITLE
Not working in 1.18

### ISSUE THREAD

**Issue by TMulderNL** [Fourmisain/KeepHeadNames#2]
Server crashes on start when this mod is added to the modlist.

**Comment by Fourmisain** [comment]
Works just fine for me, crashlog please!
(It's found in the `crash-reports` folder, alternatively the `latest.log` from the `logs` folder should contain the relevant data too.)

Some basic troubleshooting for the meantime:
Are you using the newest Fabric Loader 0.12.8? If not, you need to install it via the [Fabric Installer](https://fabricmc.net/use/).
Do you have Fabric API installed? It should be version 0.43.1+1.18.

**Comment by Fourmisain** [comment]
This is likely the same issue as #3.

**tl;dr** It's necessary to use the newest Fabric **Installer** to install everything properly, so please try installing Fabric with the newest installer (0.10+) from https://fabricmc.net/use/ again.

**Comment by Fourmisain** [comment]
Gonna close this for now, feel free to report back if this is still an issue!
