### ISSUE TITLE
1.18 Server Crashes on Boot

### ISSUE THREAD

**Issue by LunchBox951** [Fourmisain/KeepHeadNames#3]
Will crash when this mod is in the mods folder
[latest.log](https://github.com/Fourmisain/KeepHeadNames/files/7639068/latest.log)

**Comment by Fourmisain** [comment]
This was confusing me, so I did some reading up on that, while you are using the newest Fabric Loader, it is necessary to use the newest **installer** to install it properly.

The indicator for this is this:

> Source=file:/E:/Games/Minecraft%20Server%202%20Electric%20Boogaloo/fabric-server-launch.jar

This should look something like this instead:

> Source=file:/D:/Games/Minecraft/Fabric%201.18/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar

Please try installing fabric again with the newest installer (0.10+) from https://fabricmc.net/use/

**Comment by LunchBox951** [comment]
this worked, thank you
